### ISSUE TITLE
storage-as-an-object

### ISSUE THREAD

**Issue by ropg** [akcyp/local-session-storage-proxy#6]
Not really an issue, just wanted to tell you that I built something very much inspired by your code. Its writes are debounced, the strict mode is gone and I rewrote to make the code more readable (to me, anyway).

It's [here](https://github.com/ropg/storage-as-an-object) if you want to have a look. I also made a companion [CompressedStorage](https://github.com/ropg/compressedstorage) object that you may find useful.

**Comment by akcyp** [comment]
I am very pleased that my work turned out to be useful or inspiring. I never assumed that this library would be widely used because just writing it was an experiment with ES6 proxy for me. Fingers crossed for the development of the project ✨ 
PS: the first link does not work, but the second repository code looks good 👍

**Comment by ropg** [comment]
Duh, left repo on private. Fixed. 😳

Not sure mine will be much used either, but I needed the functionality but with the debounce, and I also wanted to learn about proxies etc.
